version: '3.8'

services:
  app:
    build:
      context: ./app
    command: python main.py
    expose:
      - "8000"
      - "8001"
    restart: always
    environment:
      - LOG_LEVEL=info
    networks:
      - caffe-network

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - caffe-network

networks:
  caffe-network:
    driver: bridge