services:
  app:
    build:
      context: ./app
    command: python main.py
    expose:
      - "8000"
      - "8001"
    restart: always
    environment:
      - LOG_LEVEL=info
    networks:
      - caffe-network

  nginx:
    build:
      context: ./nginx
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - caffe-network

networks:
  caffe-network:
    driver: bridge